package tetz42.validation;

public enum FailureType {
	OK, REQUIRED, FORMAT_NOT_NUMERIC, FORMAT_NOT_ALPHABETIC, FORMAT_NOT_ALPHANUEMERIC, LENGTH_TOO_LONG, LENGTH_TOO_SHORT, BYTELENGTH_TOO_LONG, BYTELENGTH_TOO_SHORT
}
